import { resolve } from "node:path";
import { defineConfig } from "@playwright/test";

/** Generated by global-setup.ts: voice-like syllables over room noise on a known timeline. */
export const VOICE_FIXTURE = resolve(process.cwd(), "test/browser/.fixtures/voice.wav");
/** Room noise only — for tests that must prove the gate stays quiet. */
export const SILENCE_FIXTURE = resolve(process.cwd(), "test/browser/.fixtures/silence.wav");
export const FAKE_MEDIA_ARGS = ["--use-fake-device-for-media-stream", "--use-fake-ui-for-media-stream"];

/**
 * Browser suite: the built package running in real Chromium against a fake
 * capture device. This is where the stateful half of the library is tested —
 * lifecycle, transport, sensing — because that is where every serious 0.1.0
 * bug lived and none of it can be exercised without a real AudioContext.
 *
 * Two traps, both of which make a broken lifecycle look green:
 *
 * 1. NEVER add `--autoplay-policy=no-user-gesture-required` here. It disables the
 * suspended-context behaviour the lifecycle tests exist to verify; tests that
 * need a gesture click the harness button, which Playwright dispatches as a
 * trusted event.
 *
 * 2. `page.evaluate` itself runs with a user gesture, and activation is sticky
 *    for the document. Anything that must be observed WITHOUT activation — the
 *    locked state, unlock() failing outside a gesture — has to run from script
 *    the page owns, before any evaluate touches it. See `?scenario=locked` in
 *    harness.html. Measure it, then evaluate; never the other way round.
 */
export default defineConfig({
  testDir: "test/browser",
  globalSetup: "./test/browser/global-setup.ts",
  timeout: 20_000,
  fullyParallel: false,
  reporter: process.env.CI ? "github" : "list",
  webServer: {
    command: "node test/browser/serve.mjs",
    port: 4173,
    reuseExistingServer: !process.env.CI,
  },
  use: {
    baseURL: "http://127.0.0.1:4173",
    browserName: "chromium",
    launchOptions: {
      // Chromium's built-in fake device only beeps. This plays our fixture on loop instead.
      args: [...FAKE_MEDIA_ARGS, `--use-file-for-fake-audio-capture=${VOICE_FIXTURE}`],
    },
  },
});
